### ISSUE TITLE
[Bug]: Crash on Quick Match with iTunes: *TypeError: matchData[key].split is not a function*

### ISSUE THREAD

**Issue by raphaelporsche** [advplyr/audiobookshelf#1025]
### Describe the issue

Quick Match an audiobook when metadata provider is set to iTunes crashes audiobookshelf:

```
audiobookshelf_1  | /server/libs/njodb/index.js:103
audiobookshelf_1  |         throw error;
audiobookshelf_1  |         ^
audiobookshelf_1  |
audiobookshelf_1  | TypeError: matchData[key].split is not a function
audiobookshelf_1  |     at Scanner.quickMatchBookBuildUpdatePayload (/server/scanner/Scanner.js:800:58)
audiobookshelf_1  |     at Scanner.quickMatchLibraryItem (/server/scanner/Scanner.js:710:34)
audiobookshelf_1  |     at async ApiRouter.match (/server/controllers/LibraryItemController.js:240:23)
audiobookshelf_audiobookshelf_1 exited with code 7
```

### Steps to reproduce the issue

1. Set metadata provider to iTunes
2. Quick Match an audio book

### Audiobookshelf version

2.1.5

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.0](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.0)
