### ISSUE TITLE
[Bug]: Crash on adding podcast

### ISSUE THREAD

**Issue by raubreywhite** [advplyr/audiobookshelf#1290]
### Describe the issue

The server crashes whenever I try to add a podcast.

```
2022-12-19 07:58:09 audiobookshelf-audiobookshelf-1  | 
2022-12-19 07:58:09 audiobookshelf-audiobookshelf-1  | > audiobookshelf@2.2.10 start
2022-12-19 07:58:09 audiobookshelf-audiobookshelf-1  | > node index.js
2022-12-19 07:58:09 audiobookshelf-audiobookshelf-1  | 
2022-12-19 07:58:10 audiobookshelf-audiobookshelf-1  | Config /config /metadata
2022-12-19 07:58:10 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:10]  INFO: === Starting Server ===
2022-12-19 07:58:10 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:10]  INFO: [Server] Init v2.2.10
2022-12-19 07:58:10 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:10]  INFO: [DB] 0 Collections Loaded
2022-12-19 07:58:10 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:10]  INFO: [DB] 0 Playlists Loaded
2022-12-19 07:58:10 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:10]  INFO: [DB] 1 Users Loaded
2022-12-19 07:58:10 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:10]  INFO: [DB] 2 Libraries Loaded
2022-12-19 07:58:10 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:10]  INFO: [DB] 4 Authors Loaded
2022-12-19 07:58:10 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:10]  INFO: [DB] 3 Series Loaded
2022-12-19 07:58:10 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:10]  INFO: [DB] 5 Library Items Loaded
2022-12-19 07:58:11 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:11]  INFO: [BackupManager] 0 Backups Found
2022-12-19 07:58:11 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:11]  INFO: [BackupManager] Auto Backups are disabled
2022-12-19 07:58:11 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:11]  INFO: [LogManager] Init current daily log filename: 2022-12-19.txt
2022-12-19 07:58:11 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:11]  INFO: [Watcher] Initializing watcher for "Audiobooks".
2022-12-19 07:58:11 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:11]  INFO: [Watcher] Initializing watcher for "Podcasts".
2022-12-19 07:58:11 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:11]  INFO: Listening on port :80
2022-12-19 07:58:11 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:11]  INFO: [Watcher] "Podcasts" Ready
2022-12-19 07:58:12 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:12]  INFO: [Server] Socket Connected MMVeZcybrMnvIfVLAAAB
2022-12-19 07:58:12 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:12]  INFO: [Watcher] "Audiobooks" Ready
2022-12-19 07:58:13 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:13]  INFO: [Server] Socket Connected L_J36p6j7TVegardAAAD
2022-12-19 07:58:14 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:14]  INFO: [Server] Socket Connected 0wiMm90mfUskJs2iAAAF
2022-12-19 07:58:16 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:16]  INFO: [Server] Socket Connected QJPwve3JcwHxkQ3vAAAH
2022-12-19 07:58:27 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:27]  INFO: [Watcher] Re-Initializing watcher for "Podcasts".
2022-12-19 07:58:27 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:27]  INFO: [Watcher] Initializing watcher for "Podcasts".
2022-12-19 07:58:27 audiobookshelf-audiobookshelf-1  | [2022-12-19 06:58:27]  INFO: [Watcher] "Podcasts" Ready
2022-12-19 07:58:40 audiobookshelf-audiobookshelf-1  | /server/libs/njodb/index.js:103
2022-12-19 07:58:40 audiobookshelf-audiobookshelf-1  |         throw error;
2022-12-19 07:58:40 audiobookshelf-audiobookshelf-1  |         ^
2022-12-19 07:58:40 audiobookshelf-audiobookshelf-1  | 
2022-12-19 07:58:40 audiobookshelf-audiobookshelf-1  | TypeError: Cannot read properties of null (reading 'replace')
2022-12-19 07:58:40 audiobookshelf-audiobookshelf-1  |     at ApiRouter.create (/server/controllers/PodcastController.js:33:36)
2022-12-19 07:58:40 audiobookshelf-audiobookshelf-1  |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
2022-12-19 07:58:40 audiobookshelf-audiobookshelf-1  |     at next (/node_modules/express/lib/router/route.js:144:13)
2022-12-19 07:58:40 audiobookshelf-audiobookshelf-1  |     at Route.dispatch (/node_modules/express/lib/router/route.js:114:3)
2022-12-19 07:58:40 audiobookshelf-audiobookshelf-1  |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
2022-12-19 07:58:40 audiobookshelf-audiobookshelf-1  |     at /node_modules/express/lib/router/index.js:284:15
2022-12-19 07:58:40 audiobookshelf-audiobookshelf-1  |     at Function.process_params (/node_modules/express/lib/router/index.js:346:12)
2022-12-19 07:58:40 audiobookshelf-audiobookshelf-1  |     at next (/node_modules/express/lib/router/index.js:280:10)
2022-12-19 07:58:40 audiobookshelf-audiobookshelf-1  |     at expressInit (/node_modules/express/lib/middleware/init.js:40:5)
2022-12-19 07:58:40 audiobookshelf-audiobookshelf-1  |     at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
```

### Steps to reproduce the issue

Podcasts > Search > "Blowback"

<img width="869" alt="image" src="https://user-images.githubusercontent.com/1532091/208366695-06863bda-86e7-44a8-a38d-920434c7a5e9.png">

Click on "Submit"

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/1532091/208366738-ce336ea4-7a74-4f6d-ad50-5e80f03ea228.png">

And then the server crashes.

<img width="1121" alt="image" src="https://user-images.githubusercontent.com/1532091/208366573-7f5d5f58-4e92-4efa-96a9-f3470f039b94.png">

### Audiobookshelf version

v2.2.10

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.11](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.11)
