### ISSUE TITLE
[Bug]: Removing book from host before removing from server seems to crash ABS

### ISSUE THREAD

**Issue by ceramicwhite** [advplyr/audiobookshelf#1386]
### Describe the issue

I removed author folder from host and it seemed to crash ABS when watcher ran and Title was missing

```
Tom Clancy
└── Without Remorse - 1993
    ├── 06 - Without Remorse.doc.pdf
    ├── cover.jpg
    ├── metadata.abs
    └── '0_ Prologue.mp3'
```

```
[2023-01-10 19:26:19] DEBUG: [Watcher] Modified file in library "Audiobooks" and folder "fol_a5dy1w1xjdj6mi640z" with relPath "/Tom Clancy/Without Remorse - 1993/1_ Chapter 20 - Depressurization.mp3" (Watcher.js:174)
[2023-01-10 19:26:23] INFO: [Server] 42 Files Changed
[2023-01-10 19:26:23] DEBUG: [Scanner] Scanning file update groups in folder "fol_a5dy1w1xjdj6mi640z" of library "Audiobooks" (Scanner.js:542)
[2023-01-10 19:26:23] DEBUG: [Scanner] scanFolderUpdates fileUpdateGroup {
  'Tom Clancy/Without Remorse - 1993': [
    '2_ Epilogue.mp3',
    '06 - Without Remorse.doc.pdf',
    '0_ Prologue.mp3',
    '1_ Chapter 05 - Commitments.mp3',
    '1_ Chapter 12 - Outfitters.mp3',
    '1_ Chapter 01 - Enfant Perdu.mp3',
    '1_ Chapter 08 - Concealment.mp3',
    '1_ Chapter 04 - First Light.mp3',
    '1_ Chapter 07 - Recovery.mp3',
    '1_ Chapter 10 - Pathology.mp3',
    '1_ Chapter 25 - Departures.mp3',
    '1_ Chapter 24 - Hellos.mp3',
    '1_ Chapter 21 - Possibilities.mp3',
    '1_ Chapter 33 - Poisoned Charm.mp3',
    '1_ Chapter 23 - Altruism.mp3',
    '1_ Chapter 31 - Home is the Hunter.mp3',
    '1_ Chapter 18 - Interference.mp3',
    '1_ Chapter 02 - Encounters.mp3',
    '1_ Chapter 30 - Travel Agents.mp3',
    '1_ Chapter 22 - Titles.mp3',
    '1_ Chapter 15 - Lessons Applied.mp3',
    '1_ Chapter 32 - Home is the Prey.mp3',
    '1_ Chapter 14 - Lessons Learned.mp3',
    '1_ Chapter 34 - Stalking.mp3',
    '1_ Chapter 27 - Insertion.mp3',
    '1_ Chapter 16 - Exercises.mp3',
    '1_ Chapter 26 - Transit.mp3',
    '1_ Chapter 28 - First In.mp3',
    '1_ Chapter 11 - Fabrication.mp3',
    '1_ Chapter 09 - Labor.mp3',
    '1_ Chapter 17 - Complications.mp3',
    '1_ Chapter 35 - Rite of Passage.mp3',
    '1_ Chapter 03 - Captivity.mp3',
    '1_ Chapter 06 - Ambush.mp3',
    '1_ Chapter 19 - Quantity of Mercy.mp3',
    '1_ Chapter 37 - Trial by Ordeal.mp3',
    '1_ Chapter 29 - Last Out.mp3',
    '1_ Chapter 13 - Agendas.mp3',
    '1_ Chapter 36 - Dangerous Drugs.mp3',
    '1_ Chapter 20 - Depressurization.mp3',
    'Tom Clancy/Without Remorse - 1993/metadata.abs',
    'Tom Clancy/Without Remorse - 1993/cover.jpg'
  ]
} (Scanner.js:543)
[2023-01-10 19:26:23] DEBUG: [Scanner] Folder update group must be a new item "Tom Clancy/Without Remorse - 1993" in library "Audiobooks" (Scanner.js:619)
/app/server/libs/njodb/index.js:103
        throw error;
        ^

TypeError: this.filePathToPOSIX is not a function
    at recurseFiles (/app/server/utils/fileUtils.js:83:15)
    at getLibraryItemFileData (/app/server/utils/scandir.js:386:23)
    at Scanner.scanPotentialNewLibraryItem (/app/server/scanner/Scanner.js:634:35)
    at Scanner.scanFolderUpdates (/app/server/scanner/Scanner.js:621:39)
    at async Scanner.scanFilesChanged (/app/server/scanner/Scanner.js:529:31)
    at async Server.filesChanged (/app/server/Server.js:264:5)
```

### Steps to reproduce the issue

1. Remove author folder & accompanying titles from host while server is running

### Audiobookshelf version

v2.2.12

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Are you sure you are running the latest version? That error log looks like it is from an edge version before 2.2.12

**Comment by ceramicwhite** [comment]
@advplyr ahh you are right. That one I use an ffmpeg with libfdk_aac added to the image my bad.
