### ISSUE TITLE
Server crashing 

### ISSUE THREAD

**Issue by scorpio862** [advplyr/audiobookshelf#17]
After last update, the Audiobookshelf container started crashing. This is the log:

```
> audiobookshelf@1.0.2 start /
> node index.js

[2021-09-05T11:44:17.239Z] INFO: Log Level: 2
Config /config /metadata /audiobooks
[2021-09-05T11:44:17.325Z] INFO: === Starting Server ===
[2021-09-05T11:44:17.325Z] INFO: [Server] Init
[2021-09-05T11:44:17.326Z] INFO: Removing Orphan Stream downloads
[2021-09-05T11:44:17.349Z] INFO: Users Loaded 2
[2021-09-05T11:44:17.351Z] INFO: Audiobooks Loaded 21
[2021-09-05T11:44:17.351Z] ERROR: [DB] Insert settings Failed TypeError: Not an array

[2021-09-05T11:44:17.352Z] INFO: [FolderWatcher] Initializing..
[2021-09-05T11:44:17.356Z] INFO: Running on http://0.0.0.0:80
[2021-09-05T11:44:17.400Z] INFO: [FolderWatcher] Ready
[2021-09-05T11:58:16.380Z] INFO: [SOCKET] Socket Connected QFZg3yU2QbosaSicAAAB
[2021-09-05T11:58:31.082Z] INFO: [SOCKET] Socket Connected -UG5BCuZRUaHsnZIAAAD
/server/StreamManager.js:125
Logger.error('No stream for client', client.user.id)

^

TypeError: Cannot read property 'id' of undefined
at StreamManager.streamUpdate (/server/StreamManager.js:125:56)
at Socket.<anonymous> (/server/Server.js:190:66)
at Socket.emit (events.js:314:20)
at Socket.emitUntyped (/node_modules/socket.io/dist/typed-events.js:69:22)
at /node_modules/socket.io/dist/socket.js:428:39
at processTicksAndRejections (internal/process/task_queues.js:79:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! audiobookshelf@1.0.2 start: `node index.js`
npm ERR! Exit status 1


npm ERR! Failed at the audiobookshelf@1.0.2 start script.

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! /root/.npm/_logs/2021-09-05T11_58_36_116Z-debug.log
```

**Comment by advplyr** [comment]
Just pushed a fix for that for v1.0.4
