### ISSUE TITLE
[Bug]: Quickmatching Podcast Episodes Results in Crash

### ISSUE THREAD

**Issue by Ruthalas** [advplyr/audiobookshelf#1711]
### Describe the issue

In a library of the type "Podcast", when I open a podcast that has already been successfully matched, click the triple dot, and click "Quick match all episodes" the docker immediately crashes with the following message in the log:

```
/server/libs/njodb/index.js:103
throw error;

TypeError: Cannot convert undefined or null to object
at Function.keys (<anonymous>)
at areEquivalent (/server/utils/areEquivalent.js:104:24)
at PodcastEpisode.update (/server/objects/entities/PodcastEpisode.js:151:41)
at Podcast.updateEpisode (/server/objects/mediaTypes/Podcast.js:158:20)
at Scanner.updateEpisodeWithMatch (/server/scanner/Scanner.js:935:32)
at Scanner.quickMatchPodcastEpisodes (/server/scanner/Scanner.js:899:33)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async ApiRouter.quickMatchEpisodes (/server/controllers/PodcastController.js:200:29)
```

I have tried this with the the following podcasts, among others:
https://podcasts.apple.com/us/podcast/black-box-down/id1503540842
https://podcasts.apple.com/us/podcast/safety-third/id1384744770

### Steps to reproduce the issue

1. Create podcast type library
2. Scan/add podcast
3. Match podcast
4. Navigate to podcast, click triple dots, select "Quick match all episodes"

### Audiobookshelf version

v2.2.19

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.2.20](https://github.com/advplyr/audiobookshelf/releases/tag/v2.2.20)
