### ISSUE TITLE
open a series > this page could not be found

### ISSUE THREAD

**Issue by skyzuma** [advplyr/audiobookshelf#1914]
### Steps to reproduce

1. open latest (0.9.65-beta) mobile app
2. go to series tab
3. open any series

### Expected behaviour
open the series

### Actual behaviour

> TypeError: Cannot read properties of undefined (reading 'checkCanAccessLibrary')
    at checkCanAccessLibraryItem (/server/objects/user/User.js:361:15)
    at Array.filter (<anonymous>)
    at ApiRouter.middleware (/server/controllers/SeriesController.js:73:49)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at /node_modules/express/lib/router/index.js:284:15
    at param (/node_modules/express/lib/router/index.js:365:14)
    at param (/node_modules/express/lib/router/index.js:376:14)

![Screenshot_20230716_141052_com audiobookshelf app](https://github.com/advplyr/audiobookshelf-app/assets/1676196/a7a01646-5cf0-4aba-81bf-c63a6e116ac9)

### Environment data

Audiobookshelf Version: 2.3.0

- [x] Android App?

#### Android Issue
Android version:  9.1.0 / 11

Device model: Huawai P10 / SM-T725

Stock or customized system: Stock

**Comment by advplyr** [comment]
Just fixed this one and will patch today

**Comment by advplyr** [comment]
Fixed in [v2.3.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.3.1)

**Comment by skyzuma** [comment]
sucessfully ...
