### ISSUE TITLE
[Bug]: Crashing entirely

### ISSUE THREAD

**Issue by barelylit** [advplyr/audiobookshelf#2006]
### Describe the issue

Ive had the server crash entirely lately, i forgot to get the logs last time, but this time it is :

`2023-08-14 19:05:08 Error: ENOSYS: function not implemented, stat '/audiobooks/Ben Elton/Two Brothers/Disc 08 - 15 - Track15.mp3'
2023-08-14 19:05:08 Error: ENOSYS: function not implemented, stat '/audiobooks/Ben Elton/Two Brothers/Disc 08 - 15 - Track15.mp3'
2023-08-14 19:05:09 Error: ENOSYS: function not implemented, stat '/audiobooks/Ben Elton/Two Brothers/Disc 08 - 15 - Track15.mp3'
2023-08-14 19:05:11 Error: ENOSYS: function not implemented, stat '/audiobooks/Ben Elton/Two Brothers/Disc 08 - 15 - Track15.mp3'
2023-08-14 19:05:13 node:internal/process/promises:279
2023-08-14 19:05:13             triggerUncaughtException(err, true /* fromPromise */);
2023-08-14 19:05:13             ^
2023-08-14 19:05:13 
2023-08-14 19:05:13 Error
2023-08-14 19:05:13     at Database.<anonymous> (/node_modules/sequelize/lib/dialects/sqlite/query.js:185:27)
2023-08-14 19:05:13     at /node_modules/sequelize/lib/dialects/sqlite/query.js:183:50
2023-08-14 19:05:13     at new Promise (<anonymous>)
2023-08-14 19:05:13     at Query.run (/node_modules/sequelize/lib/dialects/sqlite/query.js:183:12)
2023-08-14 19:05:13     at /node_modules/sequelize/lib/sequelize.js:315:28
2023-08-14 19:05:13     at runMicrotasks (<anonymous>)
2023-08-14 19:05:13     at processTicksAndRejections (node:internal/process/task_queues:96:5)
2023-08-14 19:05:13     at async SQLiteQueryInterface.upsert (/node_modules/sequelize/lib/dialects/abstract/query-interface.js:341:12)
2023-08-14 19:05:13     at async Function.upsert (/node_modules/sequelize/lib/model.js:1533:20)
2023-08-14 19:05:13     at async PlaybackSessionManager.syncSession (/server/managers/PlaybackSessionManager.js:286:25) {
2023-08-14 19:05:13   name: 'SequelizeDatabaseError',
2023-08-14 19:05:13   parent: [Error: SQLITE_IOERR: disk I/O error] {
2023-08-14 19:05:13     errno: 10,
2023-08-14 19:05:13     code: 'SQLITE_IOERR',
2023-08-14 19:05:13     sql: 'INSERT INTO `mediaProgresses` (`id`,`mediaItemId`,`mediaItemType`,`duration`,`currentTime`,`isFinished`,`hideFromContinueListening`,`ebookLocation`,`ebookProgress`,`finishedAt`,`extraData`,`createdAt`,`updatedAt`,`userId`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT (`id`) DO UPDATE SET `id`=EXCLUDED.`id`,`userId`=EXCLUDED.`userId`,`mediaItemId`=EXCLUDED.`mediaItemId`,`mediaItemType`=EXCLUDED.`mediaItemType`,`duration`=EXCLUDED.`duration`,`currentTime`=EXCLUDED.`currentTime`,`ebookLocation`=EXCLUDED.`ebookLocation`,`ebookProgress`=EXCLUDED.`ebookProgress`,`isFinished`=EXCLUDED.`isFinished`,`hideFromContinueListening`=EXCLUDED.`hideFromContinueListening`,`finishedAt`=EXCLUDED.`finishedAt`,`createdAt`=EXCLUDED.`createdAt`,`updatedAt`=EXCLUDED.`updatedAt`,`extraData`=EXCLUDED.`extraData`;'
2023-08-14 19:05:13   },
2023-08-14 19:05:13   original: [Error: SQLITE_IOERR: disk I/O error] {
2023-08-14 19:05:13     errno: 10,
2023-08-14 19:05:13     code: 'SQLITE_IOERR',
2023-08-14 19:05:13     sql: 'INSERT INTO `mediaProgresses` (`id`,`mediaItemId`,`mediaItemType`,`duration`,`currentTime`,`isFinished`,`hideFromContinueListening`,`ebookLocation`,`ebookProgress`,`finishedAt`,`extraData`,`createdAt`,`updatedAt`,`userId`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT (`id`) DO UPDATE SET `id`=EXCLUDED.`id`,`userId`=EXCLUDED.`userId`,`mediaItemId`=EXCLUDED.`mediaItemId`,`mediaItemType`=EXCLUDED.`mediaItemType`,`duration`=EXCLUDED.`duration`,`currentTime`=EXCLUDED.`currentTime`,`ebookLocation`=EXCLUDED.`ebookLocation`,`ebookProgress`=EXCLUDED.`ebookProgress`,`isFinished`=EXCLUDED.`isFinished`,`hideFromContinueListening`=EXCLUDED.`hideFromContinueListening`,`finishedAt`=EXCLUDED.`finishedAt`,`createdAt`=EXCLUDED.`createdAt`,`updatedAt`=EXCLUDED.`updatedAt`,`extraData`=EXCLUDED.`extraData`;'
2023-08-14 19:05:13   },
2023-08-14 19:05:13   sql: 'INSERT INTO `mediaProgresses` (`id`,`mediaItemId`,`mediaItemType`,`duration`,`currentTime`,`isFinished`,`hideFromContinueListening`,`ebookLocation`,`ebookProgress`,`finishedAt`,`extraData`,`createdAt`,`updatedAt`,`userId`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT (`id`) DO UPDATE SET `id`=EXCLUDED.`id`,`userId`=EXCLUDED.`userId`,`mediaItemId`=EXCLUDED.`mediaItemId`,`mediaItemType`=EXCLUDED.`mediaItemType`,`duration`=EXCLUDED.`duration`,`currentTime`=EXCLUDED.`currentTime`,`ebookLocation`=EXCLUDED.`ebookLocation`,`ebookProgress`=EXCLUDED.`ebookProgress`,`isFinished`=EXCLUDED.`isFinished`,`hideFromContinueListening`=EXCLUDED.`hideFromContinueListening`,`finishedAt`=EXCLUDED.`finishedAt`,`createdAt`=EXCLUDED.`createdAt`,`updatedAt`=EXCLUDED.`updatedAt`,`extraData`=EXCLUDED.`extraData`;',
2023-08-14 19:05:13   parameters: {}
2023-08-14 19:05:13 }`

( In case github messes that, also here: https://pastebin.com/7EQAPf95 )

### Steps to reproduce the issue

1. Client was playing, suddenly stopped with error as provided

### Audiobookshelf version

2.3.3

### How are you running audiobookshelf?

Docker

**Comment by barelylit** [comment]
Had this happen again today:

2023-08-18 14:19:03 node:internal/process/promises:279
2023-08-18 14:19:03             triggerUncaughtException(err, true /* fromPromise */);
2023-08-18 14:19:03             ^
2023-08-18 14:19:03 
2023-08-18 14:19:03 Error
2023-08-18 14:19:03     at Database.<anonymous> (/node_modules/sequelize/lib/dialects/sqlite/query.js:185:27)
2023-08-18 14:19:03     at Database.serialize (<anonymous>)
2023-08-18 14:19:03     at /node_modules/sequelize/lib/dialects/sqlite/query.js:183:50
2023-08-18 14:19:03     at new Promise (<anonymous>)
2023-08-18 14:19:03     at Query.run (/node_modules/sequelize/lib/dialects/sqlite/query.js:183:12)
2023-08-18 14:19:03     at /node_modules/sequelize/lib/sequelize.js:315:28
2023-08-18 14:19:03     at async SQLiteQueryInterface.upsert (/node_modules/sequelize/lib/dialects/abstract/query-interface.js:341:12)
2023-08-18 14:19:03     at async Function.upsert (/node_modules/sequelize/lib/model.js:1533:20)
2023-08-18 14:19:03     at async PlaybackSessionManager.syncLocalSession (/server/managers/PlaybackSessionManager.js:176:25)
2023-08-18 14:19:03     at async PlaybackSessionManager.syncLocalSessionRequest (/server/managers/PlaybackSessionManager.js:192:20) {
2023-08-18 14:19:03   name: 'SequelizeDatabaseError',
2023-08-18 14:19:03   parent: [Error: SQLITE_CANTOPEN: unable to open database file] {
2023-08-18 14:19:03     errno: 14,
2023-08-18 14:19:03     code: 'SQLITE_CANTOPEN',
2023-08-18 14:19:03     sql: 'INSERT INTO `mediaProgresses` (`id`,`mediaItemId`,`mediaItemType`,`duration`,`currentTime`,`isFinished`,`hideFromContinueListening`,`ebookLocation`,`ebookProgress`,`finishedAt`,`extraData`,`createdAt`,`updatedAt`,`userId`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT (`id`) DO UPDATE SET `id`=EXCLUDED.`id`,`userId`=EXCLUDED.`userId`,`mediaItemId`=EXCLUDED.`mediaItemId`,`mediaItemType`=EXCLUDED.`mediaItemType`,`duration`=EXCLUDED.`duration`,`currentTime`=EXCLUDED.`currentTime`,`ebookLocation`=EXCLUDED.`ebookLocation`,`ebookProgress`=EXCLUDED.`ebookProgress`,`isFinished`=EXCLUDED.`isFinished`,`hideFromContinueListening`=EXCLUDED.`hideFromContinueListening`,`finishedAt`=EXCLUDED.`finishedAt`,`createdAt`=EXCLUDED.`createdAt`,`updatedAt`=EXCLUDED.`updatedAt`,`extraData`=EXCLUDED.`extraData`;'
2023-08-18 14:19:03   },
2023-08-18 14:19:03   original: [Error: SQLITE_CANTOPEN: unable to open database file] {
2023-08-18 14:19:03     errno: 14,
2023-08-18 14:19:03     code: 'SQLITE_CANTOPEN',
2023-08-18 14:19:03     sql: 'INSERT INTO `mediaProgresses` (`id`,`mediaItemId`,`mediaItemType`,`duration`,`currentTime`,`isFinished`,`hideFromContinueListening`,`ebookLocation`,`ebookProgress`,`finishedAt`,`extraData`,`createdAt`,`updatedAt`,`userId`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT (`id`) DO UPDATE SET `id`=EXCLUDED.`id`,`userId`=EXCLUDED.`userId`,`mediaItemId`=EXCLUDED.`mediaItemId`,`mediaItemType`=EXCLUDED.`mediaItemType`,`duration`=EXCLUDED.`duration`,`currentTime`=EXCLUDED.`currentTime`,`ebookLocation`=EXCLUDED.`ebookLocation`,`ebookProgress`=EXCLUDED.`ebookProgress`,`isFinished`=EXCLUDED.`isFinished`,`hideFromContinueListening`=EXCLUDED.`hideFromContinueListening`,`finishedAt`=EXCLUDED.`finishedAt`,`createdAt`=EXCLUDED.`createdAt`,`updatedAt`=EXCLUDED.`updatedAt`,`extraData`=EXCLUDED.`extraData`;'
2023-08-18 14:19:03   },
2023-08-18 14:19:03   sql: 'INSERT INTO `mediaProgresses` (`id`,`mediaItemId`,`mediaItemType`,`duration`,`currentTime`,`isFinished`,`hideFromContinueListening`,`ebookLocation`,`ebookProgress`,`finishedAt`,`extraData`,`createdAt`,`updatedAt`,`userId`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT (`id`) DO UPDATE SET `id`=EXCLUDED.`id`,`userId`=EXCLUDED.`userId`,`mediaItemId`=EXCLUDED.`mediaItemId`,`mediaItemType`=EXCLUDED.`mediaItemType`,`duration`=EXCLUDED.`duration`,`currentTime`=EXCLUDED.`currentTime`,`ebookLocation`=EXCLUDED.`ebookLocation`,`ebookProgress`=EXCLUDED.`ebookProgress`,`isFinished`=EXCLUDED.`isFinished`,`hideFromContinueListening`=EXCLUDED.`hideFromContinueListening`,`finishedAt`=EXCLUDED.`finishedAt`,`createdAt`=EXCLUDED.`createdAt`,`updatedAt`=EXCLUDED.`updatedAt`,`extraData`=EXCLUDED.`extraData`;',
2023-08-18 14:19:03   parameters: {}
2023-08-18 14:19:03 }

**Comment by hczv** [comment]
Looks like an I/O error on disk,
are you using some kind of remote storage solution to store the sqlite database?
If not, could you check your disk for defects? also give the SMART record a look :)

**Comment by advplyr** [comment]
I'm pretty sure this has been fixed since that version but let me know if it persists

**Comment by jamescochran** [comment]
I found my way here because I'm having the same issue. I was getting random crashes anytime I used it. Today I checked the docker log (I'm on 2.4.4 using linuxserver.io container). 

`node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error
    at Database.<anonymous> (/node_modules/sequelize/lib/dialects/sqlite/query.js:185:27)
    at /node_modules/sequelize/lib/dialects/sqlite/query.js:183:50
    at new Promise (<anonymous>)
    at Query.run (/node_modules/sequelize/lib/dialects/sqlite/query.js:183:12)
    at /node_modules/sequelize/lib/sequelize.js:315:28
    at async SQLiteQueryInterface.upsert (/node_modules/sequelize/lib/dialects/abstract/query-interface.js:341:12)
    at async Function.upsert (/node_modules/sequelize/lib/model.js:1533:20)
    at async PlaybackSessionManager.syncSession (/server/managers/PlaybackSessionManager.js:286:25)
    at async PlaybackSessionManager.syncSessionRequest (/server/managers/PlaybackSessionManager.js:71:9) {
  name: 'SequelizeDatabaseError',
  parent: [Error: SQLITE_CANTOPEN: unable to open database file] {
    errno: 14,
    code: 'SQLITE_CANTOPEN',
    sql: 'INSERT INTO `mediaProgresses` (`id`,`mediaItemId`,`mediaItemType`,`duration`,`currentTime`,`isFinished`,`hideFromContinueListening`,`ebookLocation`,`ebookProgress`,`finishedAt`,`extraData`,`createdAt`,`updatedAt`,`userId`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT (`id`) DO UPDATE SET `id`=EXCLUDED.`id`,`userId`=EXCLUDED.`userId`,`mediaItemId`=EXCLUDED.`mediaItemId`,`mediaItemType`=EXCLUDED.`mediaItemType`,`duration`=EXCLUDED.`duration`,`currentTime`=EXCLUDED.`currentTime`,`ebookLocation`=EXCLUDED.`ebookLocation`,`ebookProgress`=EXCLUDED.`ebookProgress`,`isFinished`=EXCLUDED.`isFinished`,`hideFromContinueListening`=EXCLUDED.`hideFromContinueListening`,`finishedAt`=EXCLUDED.`finishedAt`,`createdAt`=EXCLUDED.`createdAt`,`updatedAt`=EXCLUDED.`updatedAt`,`extraData`=EXCLUDED.`extraData`;'
  },
  original: [Error: SQLITE_CANTOPEN: unable to open database file] {
    errno: 14,
    code: 'SQLITE_CANTOPEN',
    sql: 'INSERT INTO `mediaProgresses` (`id`,`mediaItemId`,`mediaItemType`,`duration`,`currentTime`,`isFinished`,`hideFromContinueListening`,`ebookLocation`,`ebookProgress`,`finishedAt`,`extraData`,`createdAt`,`updatedAt`,`userId`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT (`id`) DO UPDATE SET `id`=EXCLUDED.`id`,`userId`=EXCLUDED.`userId`,`mediaItemId`=EXCLUDED.`mediaItemId`,`mediaItemType`=EXCLUDED.`mediaItemType`,`duration`=EXCLUDED.`duration`,`currentTime`=EXCLUDED.`currentTime`,`ebookLocation`=EXCLUDED.`ebookLocation`,`ebookProgress`=EXCLUDED.`ebookProgress`,`isFinished`=EXCLUDED.`isFinished`,`hideFromContinueListening`=EXCLUDED.`hideFromContinueListening`,`finishedAt`=EXCLUDED.`finishedAt`,`createdAt`=EXCLUDED.`createdAt`,`updatedAt`=EXCLUDED.`updatedAt`,`extraData`=EXCLUDED.`extraData`;'
  },
  sql: 'INSERT INTO `mediaProgresses` (`id`,`mediaItemId`,`mediaItemType`,`duration`,`currentTime`,`isFinished`,`hideFromContinueListening`,`ebookLocation`,`ebookProgress`,`finishedAt`,`extraData`,`createdAt`,`updatedAt`,`userId`) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) ON CONFLICT (`id`) DO UPDATE SET `id`=EXCLUDED.`id`,`userId`=EXCLUDED.`userId`,`mediaItemId`=EXCLUDED.`mediaItemId`,`mediaItemType`=EXCLUDED.`mediaItemType`,`duration`=EXCLUDED.`duration`,`currentTime`=EXCLUDED.`currentTime`,`ebookLocation`=EXCLUDED.`ebookLocation`,`ebookProgress`=EXCLUDED.`ebookProgress`,`isFinished`=EXCLUDED.`isFinished`,`hideFromContinueListening`=EXCLUDED.`hideFromContinueListening`,`finishedAt`=EXCLUDED.`finishedAt`,`createdAt`=EXCLUDED.`createdAt`,`updatedAt`=EXCLUDED.`updatedAt`,`extraData`=EXCLUDED.`extraData`;',
  parameters: {}
}`
