### ISSUE TITLE
[Bug]: Cannot read properties of undefined (reading 'getAllLibraryFolderPaths')

### ISSUE THREAD

**Issue by brandonweidner** [advplyr/audiobookshelf#2065]
### Describe the issue

On a fresh docker container browser folders fails when adding a library. 

`[2023-09-09 03:42:27] INFO: [SocketAuthority] Socket Connected qX2ElDNBia25L3YEAAAB
[2023-09-09 03:42:27] INFO: [SocketAuthority] Socket Connected _yeEYuiylcViWuqjAAAD
[2023-09-09 03:42:58] INFO: [SocketAuthority] Socket qX2ElDNBia25L3YEAAAB disconnected from client "bweidner" after 30543ms (Reason: transport close)
/server/controllers/FileSystemController.js:20
    const libraryFoldersPaths = await Database.libraryModelFolder.getAllLibraryFolderPaths()
                                                                  ^
TypeError: Cannot read properties of undefined (reading 'getAllLibraryFolderPaths')
    at ApiRouter.getPaths (/server/controllers/FileSystemController.js:20:67)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at /node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/node_modules/express/lib/router/index.js:346:12)
    at next (/node_modules/express/lib/router/index.js:280:10)
    at expressInit (/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
Config /config /metadata`

![2023-09-08_21-42-50](https://github.com/advplyr/audiobookshelf/assets/119901172/0f789cb2-b3c5-43b2-812f-06da8b5105e9)

### Steps to reproduce the issue

1.  Fresh docker container
2. Add a library

### Audiobookshelf version

v2.4.0

### How are you running audiobookshelf?

Docker

**Comment by GOvEy1nw** [comment]
Yes I'm getting this too, installing v2.4.0 on Synology DSM 6.2.4

**Comment by advplyr** [comment]
Thanks, I just reproduced this. I'll probably get a patch out later today

**Comment by TaoRone** [comment]
是的，我也遇到了这个问题
Yes, I also encountered this problem

**Comment by advplyr** [comment]
Fixed in [v2.4.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.1)
