### ISSUE TITLE
[Bug]: Server crash on quick match

### ISSUE THREAD

**Issue by advplyr** [advplyr/audiobookshelf#2068]
### Describe the issue

```[2023-09-09 00:50:11] INFO: [Scanner] matchLibraryItems: Starting library match scan 131b52b2-afb3-4236-a023-76a955412d7c for Audiobooks
/server/scanner/Scanner.js:49
        var coverResult = await CoverManager.downloadCoverFromUrl(libraryItem, matchData.cover)
                          ^

ReferenceError: CoverManager is not defined
    at Scanner.quickMatchLibraryItem (/server/scanner/Scanner.js:49:27)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Scanner.matchLibraryItemsChunk (/server/scanner/Scanner.js:299:22)
    at async Scanner.matchLibraryItems (/server/scanner/Scanner.js:348:30)```
```

### Steps to reproduce the issue

1. Enable server setting to find covers
2. Quick match that actually finds a match

### Audiobookshelf version

v2.4.0

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
Fixed in [v2.4.1](https://github.com/advplyr/audiobookshelf/releases/tag/v2.4.1)
