### ISSUE TITLE
[Bug]: borrows for files cause Socket failed to connect

### ISSUE THREAD

**Issue by 65786113** [advplyr/audiobookshelf#2071]
### Describe the issue

https://www.[audiobookshelf](https://www.audiobookshelf.org/guides/docker-install).org/guides/docker-install
I install ABS2.4.0  in Synology N54l dsDSM 7.1.1-42962 Update 5 in DOCKER.
I can enter the memu to Browse for Folder,but click on it cause **Socket disconnected**,then **Sockett failed to connect**.
Docker restart automatic,I can enter the memu to Browse for Folder.the bugs repeat again and again.
I also try that in Docker Desktop.still the same issue.
I alse try install ABS latest.but still the sam issu.

### Steps to reproduce the issue

https://pixabay.com/get/g4d251a2d38fff8a07b04d947eb347544ad5a0bd5b41214dbe40e00e398874bd286206892cb511199750ff9cd8cceccb8.png
TypeError: Cannot read properties of undefined (reading 'getAllLibraryFolderPaths')
    at ApiRouter.getPaths (/server/controllers/FileSystemController.js:20:67)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at next (/node_modules/express/lib/router/route.js:144:13)
    at Route.dispatch (/node_modules/express/lib/router/route.js:114:3)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at /node_modules/express/lib/router/index.js:284:15
    at Function.process_params (/node_modules/express/lib/router/index.js:346:12)
    at next (/node_modules/express/lib/router/index.js:280:10)
    at expressInit (/node_modules/express/lib/middleware/init.js:40:5)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
Config /config /metadata
[2023-09-10 02:26:52] INFO: === Starting Server ===
[2023-09-10 02:26:52] INFO: [Server] Init v2.4.0
[2023-09-10 02:26:52] INFO: [Database] Initializing db at "/config/absdatabase.sqlite"
[2023-09-10 02:26:52] INFO: [Database] Db connection was successful
[2023-09-10 02:26:53] INFO: [Database] Db initialized with models: user, library, libraryFolder, book, podcast, podcastEpisode, libraryItem, mediaProgress, series, bookSeries, author, bookAuthor, collection, collectionBook, playlist, playlistMediaItem, device, playbackSession, feed, feedEpisode, setting
[2023-09-10 02:26:54] INFO: [BackupManager] 0 Backups Found
[2023-09-10 02:26:54] INFO: [BackupManager] Auto Backups are disabled
[2023-09-10 02:26:54] INFO: [LogManager] Init current daily log filename: 2023-09-10.txt
[2023-09-10 02:26:54] INFO: Listening on port :80
[2023-09-10 02:26:55] INFO: [SocketAuthority] Socket Connected 2zHfzdXXdUt3vWoIAAAB

### Audiobookshelf version

v2.4.0

### How are you running audiobookshelf?

Docker

**Comment by nichwall** [comment]
This was fixed in 2.4.1

**Comment by 65786113** [comment]
> This was fixed in 2.4.1

YES,i just find that ,THANKS a lot!
