### ISSUE TITLE
[Bug]: Docker exits when trying to save a new series metadata (book)

### ISSUE THREAD

**Issue by jaw8** [advplyr/audiobookshelf#2082]
### Describe the issue

[2023-09-12 00:50:31] WARN: [ApiRouter] Series id "new-1694479790779" does not exist (ApiRouter.js:595)
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error
    at Database.<anonymous> (/node_modules/sequelize/lib/dialects/sqlite/query.js:185:27)
    at /node_modules/sequelize/lib/dialects/sqlite/query.js:183:50
    at new Promise (<anonymous>)
    at Query.run (/node_modules/sequelize/lib/dialects/sqlite/query.js:183:12)
    at /node_modules/sequelize/lib/sequelize.js:315:28
    at async SQLiteQueryInterface.select (/node_modules/sequelize/lib/dialects/abstract/query-interface.js:407:12)
    at async Function.findAll (/node_modules/sequelize/lib/model.js:1140:21)
    at async Function.findOne (/node_modules/sequelize/lib/model.js:1240:12)
    at async Function.getOldByNameAndLibrary (/server/models/Series.js:106:21)
    at async ApiRouter.createAuthorsAndSeriesForItemUpdate (/server/routers/ApiRouter.js:600:30) {
  name: 'SequelizeDatabaseError',
  parent: [Error: SQLITE_ERROR: near "s": syntax error] {
    errno: 1,
    code: 'SQLITE_ERROR',
     
 "SELECT `id`, `name`, `nameIgnorePrefix`, `description`, `createdAt`, `updatedAt`, `libraryId` FROM `series` AS `series` WHERE (name = 'Remembrance of Earth's Past' COLLATE NOCASE AND `series`.`libraryId` = 'c37ea42c-92b6-4aaa-9714-da7e6a86657c') LIMIT 1;"
  },
  original: [Error: SQLITE_ERROR: near "s": syntax error] {
    errno: 1,
    code: 'SQLITE_ERROR',
     
 "SELECT `id`, `name`, `nameIgnorePrefix`, `description`, `createdAt`, `updatedAt`, `libraryId` FROM `series` AS `series` WHERE (name = 'Remembrance of Earth's Past' COLLATE NOCASE AND `series`.`libraryId` = 'c37ea42c-92b6-4aaa-9714-da7e6a86657c') LIMIT 1;"
  },
  sql: "SELECT `id`, `name`, `nameIgnorePrefix`, `description`, `createdAt`, `updatedAt`, `libraryId` FROM `series` AS `series` WHERE (name = 'Remembrance of Earth's Past' COLLATE NOCASE AND `series`.`libraryId` = 'c37ea42c-92b6-4aaa-9714-da7e6a86657c') LIMIT 1;",
  parameters: {}
}
Config /config /metadata

### Steps to reproduce the issue

1. Edit any audiobook
2. Add (+) a new series entry (does not already exist in library)
3. Click Save or Save & Close

### Audiobookshelf version

2.4.1

### How are you running audiobookshelf?

Docker

**Comment by jaw8** [comment]
Potentially related to #2076 ?

**Comment by advplyr** [comment]
Yeah it's the same issue
