### ISSUE TITLE
[Bug]: Tall Tale TV podcast fails to download

### ISSUE THREAD

**Issue by adispi** [advplyr/audiobookshelf#2499]
### Describe the issue

on searching for podcast episode for Tall Tale TV there is the following error:
[2024-01-02 05:39:21.637] ERROR: [podcastUtils] getPodcastFeed Error Error [ERR_FR_REDIRECTION_FAILURE]: Redirected request failed: Protocol "https:" not supported. Expected "http:"

    at RedirectableRequest._processResponse (/node_modules/follow-redirects/index.js:462:24)

    at ClientRequest.RedirectableRequest._onNativeResponse (/node_modules/follow-redirects/index.js:62:10)

    at Object.onceWrapper (node:events:628:26)

    at ClientRequest.emit (node:events:513:28)

    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:693:27)

    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)

    at HTTPParser.execute (<anonymous>)

    at Socket.socketOnData (node:_http_client:534:22)

    at Socket.emit (node:events:513:28)

    at addChunk (node:internal/streams/readable:315:12) {

  code: 'ERR_FR_REDIRECTION_FAILURE',

  cause: TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"

      at new NodeError (node:internal/errors:387:5)

      at new ClientRequest (node:_http_client:186:11)

      at Object.request (node:https:357:10)

      at RedirectableRequest._performRequest (/node_modules/follow-redirects/index.js:284:24)

      at RedirectableRequest._processResponse (/node_modules/follow-redirects/index.js:459:10)

      at ClientRequest.RedirectableRequest._onNativeResponse (/node_modules/follow-redirects/index.js:62:10)

      at Object.onceWrapper (node:events:628:26)

      at ClientRequest.emit (node:events:513:28)

      at HTTPParser.parserOnIncomingClient (node:_http_client:693:27)

      at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17) {

    code: 'ERR_INVALID_PROTOCOL'

  },

setting the rss as http or as https will get the same error.

server :2.7.1 - docker
running on synology.
podcast url: https://pinecast.com/feed/tall-tale-tv

### Steps to reproduce the issue

1. either search or schedule podcast https://pinecast.com/feed/tall-tale-tv 

### Audiobookshelf version

2.7.1

### How are you running audiobookshelf?

Docker

**Comment by advplyr** [comment]
I have no issue adding this podcast and downloading episodes.

The actual RSS feed URL is https://feeds.libsyn.com/460923/rss

You can see if you go to https://pinecast.com/feed/tall-tale-tv in your browser it will redirect to the actual RSS feed url

You can also just search "Tall Tale TV" and it will come up in the search.
