### ISSUE TITLE
[Bug]: Scan is not picking up files moved from one folder to another within a library

### ISSUE THREAD

**Issue by iconoclasthero** [advplyr/audiobookshelf#2823]
### Describe the issue

I moved a bunch of files from `/library/books/new` and '/library/books/opus` to `/library/books/audiobooks` and the scanner fails to pick up the changes.  All three of these directories were under the "Audiobook library" and the ones in `/library/books/new` were also in a library named "New Audiobooks." The force rescan has been removed so that is not an option.  The only thing that works is moving the files from this block device to another OR changing the files by concatenating individual files into an indexed opus if that's the way they're found.  (Can't do this with a single indexed file.)

### Steps to reproduce the issue

1. See above.

### Audiobookshelf version

2.8.1

### How are you running audiobookshelf?

Docker

**Comment by iconoclasthero** [comment]
So this fatal error that keeps happening seems to be preventing the DB from ever fully updating:
```
[Server] Unhandled rejection: Error: Bad archive, promise: Promise { <rejected> Error: Bad archive at FsRead.readUntilFoundCallback [as callback] (/server/libs/nodeStreamZip/index.js:198:33) at FsRead.readCallback (/server/libs/nodeStreamZip/index.js:996:19) at FSReqCallback.wrapper [as oncomplete] (node:fs:686:5) }
```

**Comment by iconoclasthero** [comment]
```
2024-04-06 00:39:38.694

FATAL

[Server] Unhandled rejection: Error: ENOENT: no such file or directory, open '/library/books/new/Nolan, James/Atomic Doctors: Conscience and Complicity at the Dawn of the Nuclear Age (2020)/Atomic Doctors -- eBook.epub', promise: Promise { <rejected> [Error: ENOENT: no such file or directory, open '/library/books/new/Nolan, James/Atomic Doctors: Conscience and Complicity at the Dawn of the Nuclear Age (2020)/Atomic Doctors -- eBook.epub'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/library/books/new/Nolan, James/Atomic Doctors: Conscience and Complicity at the Dawn of the Nuclear Age (2020)/Atomic Doctors -- eBook.epub' } }

2024-04-06 00:39:39.766

INFO

[Server] Init v2.8.1

2024-04-06 00:43:09.899

FATAL

[Server] Unhandled rejection: Error: ENOENT: no such file or directory, open '/library/books/new/Lemire, Jonathan/The Big Lie: Election Chaos, Political Opposition, and the State of American Politics After 2020 (2022)/The Big Lie -- eBook.epub', promise: Promise { <rejected> [Error: ENOENT: no such file or directory, open '/library/books/new/Lemire, Jonathan/The Big Lie: Election Chaos, Political Opposition, and the State of American Politics After 2020 (2022)/The Big Lie -- eBook.epub'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/library/books/new/Lemire, Jonathan/The Big Lie: Election Chaos, Political Opposition, and the State of American Politics After 2020 (2022)/The Big Lie -- eBook.epub' } }

2024-04-06 00:43:10.955

INFO

[Server] Init v2.8.1

2024-04-06 00:55:13.298

INFO

[Server] Init v2.8.1

2024-04-06 00:58:04.524

FATAL

[Server] Unhandled rejection: Error: ENOENT: no such file or directory, open '/library/books/audiobooks/Neiwert, David/The Age of Insurrection: The Radical Right's Assault on American Democracy (2023)/The Age of Insurrection_ The Ra - David Neiwert.epub', promise: Promise { <rejected> [Error: ENOENT: no such file or directory, open '/library/books/audiobooks/Neiwert, David/The Age of Insurrection: The Radical Right's Assault on American Democracy (2023)/The Age of Insurrection_ The Ra - David Neiwert.epub'] { errno: -2, code: 'ENOENT', syscall: 'open', path: "/library/books/audiobooks/Neiwert, David/The Age of Insurrection: The Radical Right's Assault on American Democracy (2023)/The Age of Insurrection_ The Ra - David Neiwert.epub" } }

2024-04-06 00:58:05.711

INFO

[Server] Init v2.8.1

2024-04-06 01:20:17.250

INFO

[Server] Init v2.8.1

2024-04-06 01:43:09.425

FATAL

[Server] Unhandled rejection: Error: Bad archive, promise: Promise { <rejected> Error: Bad archive at FsRead.readUntilFoundCallback [as callback] (/server/libs/nodeStreamZip/index.js:198:33) at FsRead.readCallback (/server/libs/nodeStreamZip/index.js:996:19) at FSReqCallback.wrapper [as oncomplete] (node:fs:686:5) }

2024-04-06 01:43:10.513

INFO

[Server] Init v2.8.1

2024-04-06 01:49:29.862

FATAL

[Server] Unhandled rejection: Error: ENOENT: no such file or directory, open '/library/books/opus/Lembke, Anna/Dopamine Nation: Finding Balance in the Age of Indulgence (2021)/Dopamine Nation -- eBook.epub', promise: Promise { <rejected> [Error: ENOENT: no such file or directory, open '/library/books/opus/Lembke, Anna/Dopamine Nation: Finding Balance in the Age of Indulgence (2021)/Dopamine Nation -- eBook.epub'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/library/books/opus/Lembke, Anna/Dopamine Nation: Finding Balance in the Age of Indulgence (2021)/Dopamine Nation -- eBook.epub' } }

2024-04-06 01:49:30.939

INFO

[Server] Init v2.8.1

2024-04-06 01:52:11.799

FATAL

[Server] Unhandled rejection: Error: ENOENT: no such file or directory, open '/library/books/new/Auerbach, David/Meganets: How Digital Forces Beyond Our Control Commandeer Our Daily Lives and Inner Realities (2023)/Meganets -- eBook.epub', promise: Promise { <rejected> [Error: ENOENT: no such file or directory, open '/library/books/new/Auerbach, David/Meganets: How Digital Forces Beyond Our Control Commandeer Our Daily Lives and Inner Realities (2023)/Meganets -- eBook.epub'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/library/books/new/Auerbach, David/Meganets: How Digital Forces Beyond Our Control Commandeer Our Daily Lives and Inner Realities (2023)/Meganets -- eBook.epub' } }

2024-04-06 01:52:12.886

INFO

[Server] Init v2.8.1

2024-04-06 01:53:54.982

FATAL

[Server] Unhandled rejection: Error: ENOENT: no such file or directory, open '/library/books/new/Bradley, James/The China Mirage: The Hidden History of American Disaster in Asia (2015)/The China Mirage -- eBook.epub', promise: Promise { <rejected> [Error: ENOENT: no such file or directory, open '/library/books/new/Bradley, James/The China Mirage: The Hidden History of American Disaster in Asia (2015)/The China Mirage -- eBook.epub'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/library/books/new/Bradley, James/The China Mirage: The Hidden History of American Disaster in Asia (2015)/The China Mirage -- eBook.epub' } }

2024-04-06 01:53:56.061

INFO

[Server] Init v2.8.1

2024-04-06 01:57:24.105

FATAL

[Server] Unhandled rejection: Error: ENOENT: no such file or directory, open '/library/books/opus/Perel, Esther/Mating in Captivity: Reconciling the Erotic and the Domestic (2006)/Mating in Captivity Unlocking Erotic Intelligence.epub', promise: Promise { <rejected> [Error: ENOENT: no such file or directory, open '/library/books/opus/Perel, Esther/Mating in Captivity: Reconciling the Erotic and the Domestic (2006)/Mating in Captivity Unlocking Erotic Intelligence.epub'] { errno: -2, code: 'ENOENT', syscall: 'open', path: '/library/books/opus/Perel, Esther/Mating in Captivity: Reconciling the Erotic and the Domestic (2006)/Mating in Captivity Unlocking Erotic Intelligence.epub' } }

2024-04-06 01:57:25.191

INFO

[Server] Init v2.8.1
```
