### ISSUE TITLE
Unhandled Promise

### ISSUE THREAD

**Issue by Budlyte** [advplyr/audiobookshelf#288]
### Steps to reproduce

1. Updated to server to v1.6.51.  I had not updated in a long time, months maybe.

### Actual behaviour
- Web UI is very very slow on loading Library, Series, and Collections, as well as results from search and filters. Home tab loads fine, but most covers do not load anymore.

### Environment data
Repeated Log Error on every attempt to change tabs.

````
(node:18) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
at validateString (internal/validators.js:120:11)
at Object.join (path.js:1039:7)
at Audiobook.fixFullCoverPath (/server/objects/Audiobook.js:1027:31)
at ApiController.getCover (/server/controllers/BookController.js:247:31)
at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
at next (/node_modules/express/lib/router/route.js:137:13)
at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)
at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
at /node_modules/express/lib/router/index.js:281:22
at param (/node_modules/express/lib/router/index.js:354:14)
(node:18) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 70)
```

**Comment by advplyr** [comment]
Have you scanned the library?

**Comment by Budlyte** [comment]
Huh, ok. Doing a Force Rescan cleared it all up.  Wild, thanks!
