### ISSUE TITLE
[Bug]: Users with Tag Restrictions Unable to access libraries

### ISSUE THREAD

**Issue by SAS-1** [advplyr/audiobookshelf#3289]
### What happened?

A normal user with a restriction to not see a specific tag when they login they get a socket error and lots of errors in console view. This also causes the server to crash.

### What did you expect to happen?

User should be able to login correctly with restricted tags. 

### Steps to reproduce the issue

1.  Setup a user with Can Access all Tags as No 
2.  Enter a Select a tag they cannot view
3. select the Invert option
4. Login to ABS using a InPrivate Window

### Audiobookshelf version

v2.12.3 (edge)

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

Edge

### Logs

```shell
FATAL

[Server] Unhandled rejection: ReferenceError: bookWhere is not defined, promise: Promise { <rejected> ReferenceError: bookWhere is not defined at Object.getUserPermissionPodcastWhereQuery (/server/utils/queries/libraryItemsPodcastFilters.js:23:9) at Object.getFilteredPodcastEpisodes (/server/utils/queries/libraryItemsPodcastFilters.js:266:45) at Object.getMediaItemsInProgress (/server/utils/queries/libraryFilters.js:67:72) at libraryItem.getPersonalizedShelves (/server/models/LibraryItem.js:600:57) at ApiRouter.getUserPersonalizedShelves (/server/controllers/LibraryController.js:575:53) at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5) at next (/node_modules/express/lib/router/route.js:144:13) at ApiRouter.middleware (/server/controllers/LibraryController.js:1016:5) }
```

### Additional Notes

Created new admin and normal users and issue remains. 
Tried with Internal Login and OpenID both have same issue
Tried with IP and Port and URL and issue is consistent between both so does not appear to be a proxy issue. 
Thanks to nichwall suggestion on Discord I checked all the Docker Tags from 2.11.0 up and the issue is on Edge only

**Comment by SAS-1** [comment]
fixed in latest edge
