### ISSUE TITLE
Bug: Invalid Token with no way to clear the session.

### ISSUE THREAD

**Issue by Budlyte** [advplyr/audiobookshelf#33]
Hello,
For one of my users this error keeps appearing in the logs. In that account I can login, but no audiobooks populate in the library.  I am able to login to other accounts and the library populates fine though.  Spacing because github won't format this correctly...

[2021-09-16T03:10:29.179Z] ERROR: Cannot validate socket - invalid token
[2021-09-16T03:10:50.580Z] ERROR: JWT Verify Token Failed TokenExpiredError: jwt expired

at /node_modules/jsonwebtoken/verify.js:152:21

at getSecret (/node_modules/jsonwebtoken/verify.js:90:14)

at Object.module.exports [as verify] (/node_modules/jsonwebtoken/verify.js:94:10)

at /server/Auth.js:80:11

at new Promise (<anonymous>)

at Auth.verifyToken (/server/Auth.js:79:12)

at Auth.authMiddleware (/server/Auth.js:48:27)

at Server.authMiddleware (/server/Server.js:123:15)

at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)

at trim_prefix (/node_modules/express/lib/router/index.js:317:13) {
expiredAt: 2021-09-03T01:22:30.000Z
}
[2021-09-16T03:10:50.580Z] ERROR: Verify Token User Not Found eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJrdDNuN2pmbCIsImlhdCI6MTYzMDYzMDM1MCwiZXhwIjoxNjMwNjMyMTUwfQ.j_KkGWHpmxozACbAjx_illP86JUiwlRWqDBapNSu9vU

**Comment by advplyr** [comment]
Make sure you have updated to the latest version and delete and recreate the user. 
This is a known bug on an early version.

**Comment by Budlyte** [comment]
That did it.   Thank you, looks like you updated just a few hour ago and fixed it.
