### ISSUE TITLE
[Bug]: Disppearing Artwork

### ISSUE THREAD

**Issue by pditty1980** [advplyr/audiobookshelf#3307]
### What happened?

audiobook covers i already added are gone after i added more artwork to different audiobooks,  i have included a picture of what they look like after the cover disappears, as you can see 2 things happen eather they revert to coverless or they actlike the cover was added but is missing

![Untitled](https://github.com/user-attachments/assets/df7cc3e0-69e0-4379-80cb-90155224c31a)

### What did you expect to happen?

Hopefully you can fix the issue, im wondering is it due to the huge size of the covers audible provides 24000x24000

### Steps to reproduce the issue

1.  i noticed this several times, so i moved the art and the metadata to the audiobook folders but its still happening

### Audiobookshelf version

v2.12.3

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Other (list in "Additional Notes" box)

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Additional Notes

I am running it on my Nas server

**Comment by advplyr** [comment]
Can you share more information on how you are running Abs? I'm assuming you are using Docker but since it seems you are not sure my first guess is this is a setup problem.

**Comment by pditty1980** [comment]
Yes I'm running it through docker on my NAS server the only difference from the norm is I created  the meta folder in main drive and got the covers & audiobook metadata in with each audiobook.

But all this is after I installed audiobookself as normal and had the same issues.

**Comment by advplyr** [comment]
The socket disconnected is an indication that the server is crashing. I'm assuming you have it setup to automatically restart on a crash?
I recommend disabling the auto-restart and when it crashes find the logs from wherever you manager the docker container on your nas. The logs will show why the crash happened.

You can also look in `/metadata/logs/crash_logs.txt`

**Comment by pditty1980** [comment]
Here is my current crash log

{"timestamp":"2024-08-14 19:31:31.148","source":"Server.js:170","message":"[Server] Unhandled rejection: RangeError: Array buffer allocation failed, promise: Promise {\n  <rejected> RangeError: Array buffer allocation failed\n      at new ArrayBuffer (<anonymous>)\n      at new Uint8Array (<anonymous>)\n      at new FastBuffer (node:internal/buffer:961:5)\n      at createUnsafeBuffer (node:internal/buffer:1064:12)\n      at Function.allocUnsafeSlow (node:buffer:413:10)\n      at FSReqCallback.readFileAfterStat [as oncomplete] (node:fs:333:31)\n}","levelName":"FATAL","level":5}
{"timestamp":"2024-08-14 19:35:50.418","source":"Server.js:170","message":"[Server] Unhandled rejection: DataCloneError: Data cannot be cloned, out of memory., promise: Promise {\n  <rejected> DOMException [DataCloneError]: Data cannot be cloned, out of memory.\n      at new DOMException (node:internal/per_context/domexception:53:5)\n      at Worker.postMessage (node:internal/worker:378:5)\n      at Archive._postMessage (/server/libs/libarchive/archive.js:233:22)\n      at Archive.open (/server/libs/libarchive/archive.js:80:27)\n      at async Object.parse (/server/utils/parsers/parseComicMetadata.js:70:19)\n      at async BookScanner.scanNewBookLibraryItem (/server/scanner/BookScanner.js:455:27)\n      at async LibraryItemScanner.scanNewLibraryItem (/server/scanner/LibraryItemScanner.js:179:24)\n      at async LibraryScanner.scanLibrary (/server/scanner/LibraryScanner.js:248:32)\n      at async LibraryScanner.scan (/server/scanner/LibraryScanner.js:82:22)\n      at async ApiRouter.scan (/server/controllers/LibraryController.js:866:5)\n}","levelName":"FATAL","level":5}
{"timestamp":"2024-08-14 20:02:07.309","source":"Server.js:170","message":"[Server] Unhandled rejection: RangeError: Array buffer allocation failed, promise: Promise {\n  <rejected> RangeError: Array buffer allocation failed\n      at new ArrayBuffer (<anonymous>)\n      at new Uint8Array (<anonymous>)\n      at new FastBuffer (node:internal/buffer:961:5)\n      at createUnsafeBuffer (node:internal/buffer:1064:12)\n      at Function.allocUnsafeSlow (node:buffer:413:10)\n      at FSReqCallback.readFileAfterStat [as oncomplete] (node:fs:333:31)\n}","levelName":"FATAL","level":5}
{"timestamp":"2024-08-14 20:07:12.895","source":"Server.js:170","message":"[Server] Unhandled rejection: RangeError: Array buffer allocation failed, promise: Promise {\n  <rejected> RangeError: Array buffer allocation failed\n      at new ArrayBuffer (<anonymous>)\n      at new Uint8Array (<anonymous>)\n      at new FastBuffer (node:internal/buffer:961:5)\n      at createUnsafeBuffer (node:internal/buffer:1064:12)\n      at Function.allocUnsafeSlow (node:buffer:413:10)\n      at FSReqCallback.readFileAfterStat [as oncomplete] (node:fs:333:31)\n}","levelName":"FATAL","level":5}
{"timestamp":"2024-08-18 08:36:11.955","source":"Server.js:170","message":"[Server] Unhandled rejection: SequelizeForeignKeyConstraintError: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed, promise: Promise {\n  <rejected> Error\n      at Database.<anonymous> (/node_modules/sequelize/lib/dialects/sqlite/query.js:185:27)\n      at /node_modules/sequelize/lib/dialects/sqlite/query.js:183:50\n      at new Promise (<anonymous>)\n      at Query.run (/node_modules/sequelize/lib/dialects/sqlite/query.js:183:12)\n      at /node_modules/sequelize/lib/sequelize.js:315:28\n      at async SQLiteQueryInterface.insert (/node_modules/sequelize/lib/dialects/abstract/query-interface.js:308:21)\n      at async BookAuthor.save (/node_modules/sequelize/lib/model.js:2490:35)\n      at async bookAuthor.create (/node_modules/sequelize/lib/model.js:1362:12)\n      at async BookScanner.rescanExistingBookLibraryItem (/server/scanner/BookScanner.js:219:15)\n      at async LibraryItemScanner.scanLibraryItem (/server/scanner/LibraryItemScanner.js:63:62) {\n    name: 'SequelizeForeignKeyConstraintError',\n    parent: [Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed] {\n      errno: 19,\n      code: 'SQLITE_CONSTRAINT',\n      sql: 'INSERT INTO `bookAuthors` (`id`,`createdAt`,`bookId`,`authorId`) VALUES ($1,$2,$3,$4);'\n    },\n    original: [Error: SQLITE_CONSTRAINT: FOREIGN KEY constraint failed] {\n      errno: 19,\n      code: 'SQLITE_CONSTRAINT',\n      sql: 'INSERT INTO `bookAuthors` (`id`,`createdAt`,`bookId`,`authorId`) VALUES ($1,$2,$3,$4);'\n    },\n    sql: 'INSERT INTO `bookAuthors` (`id`,`createdAt`,`bookId`,`authorId`) VALUES ($1,$2,$3,$4);',\n    parameters: {},\n    table: undefined,\n    fields: undefined,\n    value: undefined,\n    index: undefined,\n    reltype: undefined\n  }\n}","levelName":"FATAL","level":5}

**Comment by advplyr** [comment]
What docker image are you using? Can you share more information about your NAS setup? Maybe a screenshot of the config page or something like that.

**Comment by pditty1980** [comment]
i am using my NAS's Container manager with the latest version of Audiobookself 

![screencapture-192-168-0-72-pxd19802021-direct-quickconnect-to-5001-2024-08-19-16_47_14](https://github.com/user-attachments/assets/db29069b-81e4-46ce-982e-64aa18dac49e)

**Comment by advplyr** [comment]
Can you share the docker run command? I'm trying to see the docker image and the volumes being mapped.

**Comment by DDriggs00** [comment]
I ran into something similar to this when I performed an incomplete migration to another server. What happened was the actual images failed to be copied to the new server, but the database references to them came through. Perhaps this could have a similar cause?

**Comment by pditty1980** [comment]
> I ran into something similar to this when I performed an incomplete migration to another server. What happened was the actual images failed to be copied to the new server, but the database references to them came through. Perhaps this could have a similar cause?

Unfortunately I don't think it's that!

**Comment by thethink3r** [comment]
I have the same issue. (Only when new Abooks added)


```yaml
services:
  audiobookshelf:
    restart: unless-stopped
    image: ghcr.io/advplyr/audiobookshelf
    ports:
      - 12378:80
    volumes:
      - /volume1/Audiobooks:/audiobooks
      - /volume1/docker/audiobookshelf/config:/config
      - /volume1/docker/audiobookshelf/metadata:/metadata
```

System: Synology DS920+ 
CPU: INTEL Celeron J4125 4 Cores 
Memory: 20GB

Version lower or equal 2.11.0 works great. 
Currently i downgrade to 2.11 and i hope the bug fixed sone.

**Comment by nichwall** [comment]
Can you try using the "Clear All Cache" button in the server settings? This will force the served images to be regenerated (from the folders where the media is stored or in the `/metadata` folder).

What are the server settings here?
![Screenshot_20240903-072310.png](https://github.com/user-attachments/assets/966457eb-9573-4af2-a8d9-170434987181)
