### ISSUE TITLE
[Bug]: Podcast Episodes not updating

### ISSUE THREAD

**Issue by lethalox** [advplyr/audiobookshelf#3710]
### What happened?

I have recent setup ABS about a week ago.  I have added 108 podcasts from my Podcast Addict {android} application onto the server.   In the latest episodes, all them are from when I added the podcast to the application even though I know more episodes have been released because they release an episode everyweek.  An example is EconTalk.   Looking at the podcase there are episodes available, and they will download if I do it manually.    Attached is some screenshots.   Additionally, I notice there is error  app.  Here is the error - 

FATAL

[Server] Unhandled rejection: SyntaxError: Bad control character in string literal in JSON at position 33 at JSON.parse (<anonymous>) at parse (/node_modules/sequelize/lib/dialects/sqlite/data-types.js:34:19) at Query.applyParsers (/node_modules/sequelize/lib/dialects/sqlite/query.js:289:14) at /node_modules/sequelize/lib/dialects/sqlite/query.js:112:80 at /node_modules/lodash/lodash.js:13469:38 at /node_modules/lodash/lodash.js:4967:15 at baseForOwn (/node_modules/lodash/lodash.js:3032:24) at Function.mapValues (/node_modules/lodash/lodash.js:13468:7) at /node_modules/sequelize/lib/dialects/sqlite/query.js:93:18 at Array.map (<anonymous>) promise: Promise { <rejected> SyntaxError: Bad control character in string literal in JSON at position 33 at JSON.parse (<anonymous>) at parse (/node_modules/sequelize/lib/dialects/sqlite/data-types.js:34:19) at Query.applyParsers (/node_modules/sequelize/lib/dialects/sqlite/query.js:289:14) at /node_modules/sequelize/lib/dialects/sqlite/query.js:112:80 at /node_modules/lodash/lodash.js:13469:38 at /node_modules/lodash/lodash.js:4967:15 at baseForOwn (/node_modules/lodash/lodash.js:3032:24) at Function.mapValues (/node_modules/lodash/lodash.js:13468:7) at /node_modules/sequelize/lib/dialects/sqlite/query.js:93:18 at Array.map (<anonymous>) }

![ABS Error](https://github.com/user-attachments/assets/9ad08d1c-6030-44ba-b61e-41c34810a346)
![CWT - Detail Episodes](https://github.com/user-attachments/assets/e75229cf-595c-4c98-9e11-e36cdc17e994)
![CWT - Schedule](https://github.com/user-attachments/assets/4c3c5972-ad9b-4fa8-9775-e207cad0afbd)
![CWT Espiodes](https://github.com/user-attachments/assets/2131c12f-763a-484f-b6f1-81b9c42eb872)
![CWT Main](https://github.com/user-attachments/assets/444e88fa-a635-4a10-92a4-91e857ba8834)

### What did you expect to happen?

I expect that podcasts will be downloaded on the schedule for the individual podcast. 

### Steps to reproduce the issue

1

### Audiobookshelf version

v2.17.5

### How are you running audiobookshelf?

Docker

### What OS is your Audiobookshelf server hosted from?

Linux

### If the issue is being seen in the UI, what browsers are you seeing the problem on?

None

### Logs

```shell
FATAL

[Server] Unhandled rejection: SyntaxError: Bad control character in string literal in JSON at position 33 at JSON.parse (<anonymous>) at parse (/node_modules/sequelize/lib/dialects/sqlite/data-types.js:34:19) at Query.applyParsers (/node_modules/sequelize/lib/dialects/sqlite/query.js:289:14) at /node_modules/sequelize/lib/dialects/sqlite/query.js:112:80 at /node_modules/lodash/lodash.js:13469:38 at /node_modules/lodash/lodash.js:4967:15 at baseForOwn (/node_modules/lodash/lodash.js:3032:24) at Function.mapValues (/node_modules/lodash/lodash.js:13468:7) at /node_modules/sequelize/lib/dialects/sqlite/query.js:93:18 at Array.map (<anonymous>) promise: Promise { <rejected> SyntaxError: Bad control character in string literal in JSON at position 33 at JSON.parse (<anonymous>) at parse (/node_modules/sequelize/lib/dialects/sqlite/data-types.js:34:19) at Query.applyParsers (/node_modules/sequelize/lib/dialects/sqlite/query.js:289:14) at /node_modules/sequelize/lib/dialects/sqlite/query.js:112:80 at /node_modules/lodash/lodash.js:13469:38 at /node_modules/lodash/lodash.js:4967:15 at baseForOwn (/node_modules/lodash/lodash.js:3032:24) at Function.mapValues (/node_modules/lodash/lodash.js:13468:7) at /node_modules/sequelize/lib/dialects/sqlite/query.js:93:18 at Array.map (<anonymous>) }
```

**Comment by nichwall** [comment]
Can you provide the RSS feed for the podcast?

**Comment by lethalox** [comment]
Sure - here is the URL - https://cowenconvos.libsyn.com/rss

But, it is every podcast.   That was just an example of what I am seeing.   None of the podcasts have been updated.

**Comment by lethalox** [comment]
Update.   I notice that one my podcast "2.5 Admins", I could not get into.  When I did, I would a socket error "Socket Failed to Connect".   After some conversation it was discovered selecting that podcast was causing ABS to crash and then reboot. The RSS feed for that podcast is https://2.5admins.com/feed/.   

Thanks!

**Comment by nichwall** [comment]
I tried both of these podcasts on server version 2.17.5 and podcasts were downloaded automatically using the "automatic check" schedule.

There is probably something wrong in the database.

**Comment by rightsaidfred99** [comment]
I'm getting podcast failed all the time too, I can't provied an RSS feed because it's behind a paywall but it's the same error as the OP

**Comment by advplyr** [comment]
I think I recall this issue being fixed in Discord. Is this still an issue?
