### ISSUE TITLE
[Bug]: Audible search timing out/failing

### ISSUE THREAD

**Issue by jt196** [advplyr/audiobookshelf#973]
### Describe the issue

Doesn't look like I'm getting the Audible metadata search results in the new version of ABS. 

```
2022-09-07T09:24:25.552194887Z [2022-09-07 09:24:25] ERROR: [Audible] ASIN search error Error: Request failed with status code 504
2022-09-07T09:24:25.552856120Z     at createError (/node_modules/axios/lib/core/createError.js:16:15)
2022-09-07T09:24:25.552980642Z     at settle (/node_modules/axios/lib/core/settle.js:17:12)
2022-09-07T09:24:25.553034649Z     at IncomingMessage.handleStreamEnd (/node_modules/axios/lib/adapters/http.js:322:11)
2022-09-07T09:24:25.553093072Z     at IncomingMessage.emit (node:events:525:35)
2022-09-07T09:24:25.553142352Z     at endReadableNT (node:internal/streams/readable:1358:12)
2022-09-07T09:24:25.553192723Z     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
2022-09-07T09:24:25.553371976Z   config: {
2022-09-07T09:24:25.553449527Z     transitional: {
2022-09-07T09:24:25.553494197Z       silentJSONParsing: true,
2022-09-07T09:24:25.553539599Z       forcedJSONParsing: true,
2022-09-07T09:24:25.553586750Z       clarifyTimeoutError: false
2022-09-07T09:24:25.553632580Z     },
2022-09-07T09:24:25.553675771Z     adapter: [Function: httpAdapter],
2022-09-07T09:24:25.553720876Z     transformRequest: [ [Function: transformRequest] ],
2022-09-07T09:24:25.553766649Z     transformResponse: [ [Function: transformResponse] ],
2022-09-07T09:24:25.553810964Z     timeout: 0,
2022-09-07T09:24:25.553853919Z     xsrfCookieName: 'XSRF-TOKEN',
2022-09-07T09:24:25.553927095Z     xsrfHeaderName: 'X-XSRF-TOKEN',
2022-09-07T09:24:25.553988283Z     maxContentLength: -1,
2022-09-07T09:24:25.554032614Z     maxBodyLength: -1,
2022-09-07T09:24:25.554075320Z     validateStatus: [Function: validateStatus],
2022-09-07T09:24:25.554123549Z     headers: {
2022-09-07T09:24:25.554165596Z       Accept: 'application/json, text/plain, */*',
2022-09-07T09:24:25.554213471Z       'User-Agent': 'axios/0.26.1'
2022-09-07T09:24:25.554262484Z     },
2022-09-07T09:24:25.554417464Z     method: 'get',
2022-09-07T09:24:25.554504399Z     url: 'https://api.audnex.us/books/B01B4YRUKI',
2022-09-07T09:24:25.554560546Z     data: undefined
2022-09-07T09:24:25.554605265Z   },
2022-09-07T09:24:25.554644365Z   request: <ref *1> ClientRequest {
2022-09-07T09:24:25.554692363Z     _events: [Object: null prototype] {
2022-09-07T09:24:25.554741511Z       abort: [Function (anonymous)],
2022-09-07T09:24:25.554788657Z       aborted: [Function (anonymous)],
2022-09-07T09:24:25.554831149Z       connect: [Function (anonymous)],
2022-09-07T09:24:25.554874056Z       error: [Function (anonymous)],
2022-09-07T09:24:25.554919850Z       socket: [Function (anonymous)],
2022-09-07T09:24:25.554965579Z       timeout: [Function (anonymous)],
2022-09-07T09:24:25.555008275Z       prefinish: [Function: requestOnPrefinish]
2022-09-07T09:24:25.555053254Z     },
2022-09-07T09:24:25.555092193Z     _eventsCount: 7,
2022-09-07T09:24:25.555134540Z     _maxListeners: undefined,
2022-09-07T09:24:25.555176874Z     outputData: [],
2022-09-07T09:24:25.555218492Z     outputSize: 0,
2022-09-07T09:24:25.555259952Z     writable: true,
2022-09-07T09:24:25.555325533Z     destroyed: false,
2022-09-07T09:24:25.555371661Z     _last: true,
2022-09-07T09:24:25.555414231Z     chunkedEncoding: false,
2022-09-07T09:24:25.555543122Z     shouldKeepAlive: false,
2022-09-07T09:24:25.555601559Z     maxRequestsOnConnectionReached: false,
2022-09-07T09:24:25.555650687Z     _defaultKeepAlive: true,
2022-09-07T09:24:25.555695224Z     useChunkedEncodingByDefault: false,
2022-09-07T09:24:25.555738534Z     sendDate: false,
2022-09-07T09:24:25.555785607Z     _removedConnection: false,
2022-09-07T09:24:25.555828866Z     _removedContLen: false,
2022-09-07T09:24:25.555873496Z     _removedTE: false,
2022-09-07T09:24:25.555919314Z     _contentLength: 0,
2022-09-07T09:24:25.555961730Z     _hasBody: true,
2022-09-07T09:24:25.556003612Z     _trailer: '',
2022-09-07T09:24:25.556045515Z     finished: true,
2022-09-07T09:24:25.556095293Z     _headerSent: true,
2022-09-07T09:24:25.556138049Z     _closed: false,
2022-09-07T09:24:25.556186707Z     socket: TLSSocket {
2022-09-07T09:24:25.556230804Z       _tlsOptions: [Object],
2022-09-07T09:24:25.556273299Z       _secureEstablished: true,
2022-09-07T09:24:25.556341432Z       _securePending: false,
2022-09-07T09:24:25.556385745Z       _newSessionPending: false,
2022-09-07T09:24:25.556461552Z       _controlReleased: true,
2022-09-07T09:24:25.556508787Z       secureConnecting: false,
2022-09-07T09:24:25.556552030Z       _SNICallback: null,
2022-09-07T09:24:25.556594520Z       servername: 'api.audnex.us',
2022-09-07T09:24:25.556638277Z       alpnProtocol: false,
2022-09-07T09:24:25.556681436Z       authorized: true,
2022-09-07T09:24:25.556733022Z       authorizationError: null,
2022-09-07T09:24:25.556776153Z       encrypted: true,
2022-09-07T09:24:25.556819278Z       _events: [Object: null prototype],
2022-09-07T09:24:25.556862224Z       _eventsCount: 10,
2022-09-07T09:24:25.556903743Z       connecting: false,
2022-09-07T09:24:25.556945617Z       _hadError: false,
2022-09-07T09:24:25.556987999Z       _parent: null,
2022-09-07T09:24:25.557031033Z       _host: 'api.audnex.us',
2022-09-07T09:24:25.557074413Z       _readableState: [ReadableState],
2022-09-07T09:24:25.557117301Z       _maxListeners: undefined,
2022-09-07T09:24:25.557162351Z       _writableState: [WritableState],
2022-09-07T09:24:25.557205532Z       allowHalfOpen: false,
2022-09-07T09:24:25.557250410Z       _sockname: null,
2022-09-07T09:24:25.557360004Z       _pendingData: null,
2022-09-07T09:24:25.557405907Z       _pendingEncoding: '',
2022-09-07T09:24:25.557461382Z       server: undefined,
2022-09-07T09:24:25.557515852Z       _server: null,
2022-09-07T09:24:25.557559015Z       ssl: [TLSWrap],
2022-09-07T09:24:25.557615552Z       _requestCert: true,
2022-09-07T09:24:25.557669548Z       _rejectUnauthorized: true,
2022-09-07T09:24:25.557712853Z       parser: null,
2022-09-07T09:24:25.557771545Z       _httpMessage: [Circular *1],
2022-09-07T09:24:25.557828040Z       [Symbol(res)]: [TLSWrap],
2022-09-07T09:24:25.557874452Z       [Symbol(verified)]: true,
2022-09-07T09:24:25.557931475Z       [Symbol(pendingSession)]: null,
2022-09-07T09:24:25.557986588Z       [Symbol(async_id_symbol)]: 447144,
2022-09-07T09:24:25.558031471Z       [Symbol(kHandle)]: [TLSWrap],
2022-09-07T09:24:25.558086963Z       [Symbol(lastWriteQueueSize)]: 0,
2022-09-07T09:24:25.558141787Z       [Symbol(timeout)]: null,
2022-09-07T09:24:25.558207638Z       [Symbol(kBuffer)]: null,
2022-09-07T09:24:25.558252429Z       [Symbol(kBufferCb)]: null,
2022-09-07T09:24:25.558314766Z       [Symbol(kBufferGen)]: null,
2022-09-07T09:24:25.558368576Z       [Symbol(kCapture)]: false,
2022-09-07T09:24:25.558414750Z       [Symbol(kSetNoDelay)]: false,
2022-09-07T09:24:25.558458493Z       [Symbol(kSetKeepAlive)]: true,
2022-09-07T09:24:25.558501391Z       [Symbol(kSetKeepAliveInitialDelay)]: 60,
2022-09-07T09:24:25.558550362Z       [Symbol(kBytesRead)]: 0,
2022-09-07T09:24:25.558593513Z       [Symbol(kBytesWritten)]: 0,
2022-09-07T09:24:25.558636378Z       [Symbol(connect-options)]: [Object],
2022-09-07T09:24:25.558683279Z       [Symbol(RequestTimeout)]: undefined
2022-09-07T09:24:25.558727036Z     },
2022-09-07T09:24:25.558768569Z     _header: 'GET /books/B01B4YRUKI HTTP/1.1\r\n' +
2022-09-07T09:24:25.558819225Z       'Accept: application/json, text/plain, */*\r\n' +
2022-09-07T09:24:25.558866356Z       'User-Agent: axios/0.26.1\r\n' +
2022-09-07T09:24:25.558911273Z       'Host: api.audnex.us\r\n' +
2022-09-07T09:24:25.558958427Z       'Connection: close\r\n' +
2022-09-07T09:24:25.559002804Z       '\r\n',
2022-09-07T09:24:25.559043761Z     _keepAliveTimeout: 0,
2022-09-07T09:24:25.559086222Z     _onPendingData: [Function: nop],
2022-09-07T09:24:25.559131994Z     agent: Agent {
2022-09-07T09:24:25.559173296Z       _events: [Object: null prototype],
2022-09-07T09:24:25.559218141Z       _eventsCount: 2,
2022-09-07T09:24:25.559260761Z       _maxListeners: undefined,
2022-09-07T09:24:25.559325267Z       defaultPort: 443,
2022-09-07T09:24:25.559369681Z       protocol: 'https:',
2022-09-07T09:24:25.559414410Z       options: [Object: null prototype],
2022-09-07T09:24:25.559463473Z       requests: [Object: null prototype] {},
2022-09-07T09:24:25.559507294Z       sockets: [Object: null prototype],
2022-09-07T09:24:25.559551080Z       freeSockets: [Object: null prototype] {},
2022-09-07T09:24:25.559595566Z       keepAliveMsecs: 1000,
2022-09-07T09:24:25.559642459Z       keepAlive: false,
2022-09-07T09:24:25.559686041Z       maxSockets: Infinity,
2022-09-07T09:24:25.559729572Z       maxFreeSockets: 256,
2022-09-07T09:24:25.559773663Z       scheduling: 'lifo',
2022-09-07T09:24:25.559826976Z       maxTotalSockets: Infinity,
2022-09-07T09:24:25.559871044Z       totalSocketCount: 2,
2022-09-07T09:24:25.559914394Z       maxCachedSessions: 100,
2022-09-07T09:24:25.559958648Z       _sessionCache: [Object],
2022-09-07T09:24:25.560001007Z       [Symbol(kCapture)]: false
2022-09-07T09:24:25.560043989Z     },
2022-09-07T09:24:25.560085326Z     socketPath: undefined,
2022-09-07T09:24:25.560134041Z     method: 'GET',
2022-09-07T09:24:25.560177046Z     maxHeaderSize: undefined,
2022-09-07T09:24:25.560219307Z     insecureHTTPParser: undefined,
2022-09-07T09:24:25.560261863Z     path: '/books/B01B4YRUKI',
2022-09-07T09:24:25.560343588Z     _ended: true,
2022-09-07T09:24:25.560388986Z     res: IncomingMessage {
2022-09-07T09:24:25.560431922Z       _readableState: [ReadableState],
2022-09-07T09:24:25.560474182Z       _events: [Object: null prototype],
2022-09-07T09:24:25.560518386Z       _eventsCount: 4,
2022-09-07T09:24:25.560560659Z       _maxListeners: undefined,
2022-09-07T09:24:25.560612299Z       socket: [TLSSocket],
2022-09-07T09:24:25.560654543Z       httpVersionMajor: 1,
2022-09-07T09:24:25.560697994Z       httpVersionMinor: 1,
2022-09-07T09:24:25.560739808Z       httpVersion: '1.1',
2022-09-07T09:24:25.560781889Z       complete: true,
2022-09-07T09:24:25.560824604Z       rawHeaders: [Array],
2022-09-07T09:24:25.560868427Z       rawTrailers: [],
2022-09-07T09:24:25.560915415Z       aborted: false,
2022-09-07T09:24:25.560957691Z       upgrade: false,
2022-09-07T09:24:25.560999625Z       url: '',
2022-09-07T09:24:25.561040791Z       method: null,
2022-09-07T09:24:25.561083306Z       statusCode: 504,
2022-09-07T09:24:25.561125864Z       statusMessage: 'Gateway Timeout',
2022-09-07T09:24:25.561170643Z       client: [TLSSocket],
2022-09-07T09:24:25.561212933Z       _consuming: true,
2022-09-07T09:24:25.561268228Z       _dumped: false,
2022-09-07T09:24:25.561336771Z       req: [Circular *1],
2022-09-07T09:24:25.561385577Z       responseUrl: 'https://api.audnex.us/books/B01B4YRUKI',
2022-09-07T09:24:25.561525255Z       redirects: [],
2022-09-07T09:24:25.561568181Z       [Symbol(kCapture)]: false,
2022-09-07T09:24:25.561696402Z       [Symbol(kHeaders)]: [Object],
2022-09-07T09:24:25.561746208Z       [Symbol(kHeadersCount)]: 20,
2022-09-07T09:24:25.561792641Z       [Symbol(kTrailers)]: null,
2022-09-07T09:24:25.561836694Z       [Symbol(kTrailersCount)]: 0,
2022-09-07T09:24:25.561880579Z       [Symbol(RequestTimeout)]: undefined
2022-09-07T09:24:25.561924267Z     },
2022-09-07T09:24:25.561962526Z     aborted: false,
2022-09-07T09:24:25.562006538Z     timeoutCb: null,
2022-09-07T09:24:25.562050496Z     upgradeOrConnect: false,
2022-09-07T09:24:25.562094600Z     parser: null,
2022-09-07T09:24:25.562137113Z     maxHeadersCount: null,
2022-09-07T09:24:25.562180253Z     reusedSocket: false,
2022-09-07T09:24:25.562222546Z     host: 'api.audnex.us',
2022-09-07T09:24:25.562265821Z     protocol: 'https:',
2022-09-07T09:24:25.562341199Z     _redirectable: Writable {
2022-09-07T09:24:25.562387358Z       _writableState: [WritableState],
2022-09-07T09:24:25.562429822Z       _events: [Object: null prototype],
2022-09-07T09:24:25.562501616Z       _eventsCount: 3,
2022-09-07T09:24:25.562549534Z       _maxListeners: undefined,
2022-09-07T09:24:25.562593807Z       _options: [Object],
2022-09-07T09:24:25.562636075Z       _ended: true,
2022-09-07T09:24:25.562677640Z       _ending: true,
2022-09-07T09:24:25.562718960Z       _redirectCount: 0,
2022-09-07T09:24:25.562760870Z       _redirects: [],
2022-09-07T09:24:25.562808831Z       _requestBodyLength: 0,
2022-09-07T09:24:25.562855365Z       _requestBodyBuffers: [],
2022-09-07T09:24:25.562896994Z       _onNativeResponse: [Function (anonymous)],
2022-09-07T09:24:25.562954052Z       _currentRequest: [Circular *1],
2022-09-07T09:24:25.562999310Z       _currentUrl: 'https://api.audnex.us/books/B01B4YRUKI',
2022-09-07T09:24:25.563047824Z       [Symbol(kCapture)]: false
2022-09-07T09:24:25.563092421Z     },
2022-09-07T09:24:25.563130914Z     [Symbol(kCapture)]: false,
2022-09-07T09:24:25.563174263Z     [Symbol(kNeedDrain)]: false,
2022-09-07T09:24:25.563218376Z     [Symbol(corked)]: 0,
2022-09-07T09:24:25.563272901Z     [Symbol(kOutHeaders)]: [Object: null prototype] {
2022-09-07T09:24:25.563340190Z       accept: [Array],
2022-09-07T09:24:25.563382839Z       'user-agent': [Array],
2022-09-07T09:24:25.563426031Z       host: [Array]
2022-09-07T09:24:25.563484132Z     },
2022-09-07T09:24:25.563523425Z     [Symbol(kUniqueHeaders)]: null
2022-09-07T09:24:25.563568794Z   },
2022-09-07T09:24:25.563607529Z   response: {
2022-09-07T09:24:25.563648064Z     status: 504,
2022-09-07T09:24:25.563689400Z     statusText: 'Gateway Timeout',
2022-09-07T09:24:25.563737045Z     headers: {
2022-09-07T09:24:25.563777940Z       date: 'Wed, 07 Sep 2022 09:30:11 GMT',
2022-09-07T09:24:25.563887061Z       'content-type': 'text/html',
2022-09-07T09:24:25.563937050Z       'transfer-encoding': 'chunked',
2022-09-07T09:24:25.563982621Z       connection: 'close',
2022-09-07T09:24:25.564024493Z       'cf-cache-status': 'BYPASS',
2022-09-07T09:24:25.564076350Z       'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=Pneefqa1YhsDtXCUqmEEtkSpM4%2F7p7JCIO0L2LEtGahZiz8suW8s8binYs9bHV3klyUWfDrklUOmNdvaoW8b87D7cOnXEzVNQqjDG4z79Lo7VLDOEl83jfrsF87Pp3RP"}],"group":"cf-nel","max_age":604800}',
2022-09-07T09:24:25.564157608Z       nel: '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
2022-09-07T09:24:25.564207817Z       server: 'cloudflare',
2022-09-07T09:24:25.564250235Z       'cf-ray': '746e6b21cadcb2e5-MAN',
2022-09-07T09:24:25.564319837Z       'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400'
2022-09-07T09:24:25.564376529Z     },
2022-09-07T09:24:25.564416211Z     config: {
2022-09-07T09:24:25.564457656Z       transitional: [Object],
2022-09-07T09:24:25.564500766Z       adapter: [Function: httpAdapter],
2022-09-07T09:24:25.564553154Z       transformRequest: [Array],
2022-09-07T09:24:25.564599604Z       transformResponse: [Array],
2022-09-07T09:24:25.564641861Z       timeout: 0,
2022-09-07T09:24:25.564682581Z       xsrfCookieName: 'XSRF-TOKEN',
2022-09-07T09:24:25.564725285Z       xsrfHeaderName: 'X-XSRF-TOKEN',
2022-09-07T09:24:25.564768622Z       maxContentLength: -1,
2022-09-07T09:24:25.564809653Z       maxBodyLength: -1,
2022-09-07T09:24:25.564850472Z       validateStatus: [Function: validateStatus],
2022-09-07T09:24:25.564917959Z       headers: [Object],
2022-09-07T09:24:25.564960906Z       method: 'get',
2022-09-07T09:24:25.565002431Z       url: 'https://api.audnex.us/books/B01B4YRUKI',
2022-09-07T09:24:25.565047661Z       data: undefined
2022-09-07T09:24:25.565089549Z     },
2022-09-07T09:24:25.565127721Z     request: <ref *1> ClientRequest {
2022-09-07T09:24:25.565174411Z       _events: [Object: null prototype],
2022-09-07T09:24:25.565217566Z       _eventsCount: 7,
2022-09-07T09:24:25.565258661Z       _maxListeners: undefined,
2022-09-07T09:24:25.565348523Z       outputData: [],
2022-09-07T09:24:25.565393169Z       outputSize: 0,
2022-09-07T09:24:25.565439213Z       writable: true,
2022-09-07T09:24:25.565483444Z       destroyed: false,
2022-09-07T09:24:25.565528593Z       _last: true,
2022-09-07T09:24:25.565570475Z       chunkedEncoding: false,
2022-09-07T09:24:25.565612080Z       shouldKeepAlive: false,
2022-09-07T09:24:25.565656518Z       maxRequestsOnConnectionReached: false,
2022-09-07T09:24:25.565713265Z       _defaultKeepAlive: true,
2022-09-07T09:24:25.565755658Z       useChunkedEncodingByDefault: false,
2022-09-07T09:24:25.565797700Z       sendDate: false,
2022-09-07T09:24:25.565839544Z       _removedConnection: false,
2022-09-07T09:24:25.565885099Z       _removedContLen: false,
2022-09-07T09:24:25.565926667Z       _removedTE: false,
2022-09-07T09:24:25.565967852Z       _contentLength: 0,
2022-09-07T09:24:25.566017337Z       _hasBody: true,
2022-09-07T09:24:25.566060142Z       _trailer: '',
2022-09-07T09:24:25.566100588Z       finished: true,
2022-09-07T09:24:25.566142407Z       _headerSent: true,
2022-09-07T09:24:25.566186318Z       _closed: false,
2022-09-07T09:24:25.566227417Z       socket: [TLSSocket],
2022-09-07T09:24:25.566270052Z       _header: 'GET /books/B01B4YRUKI HTTP/1.1\r\n' +
2022-09-07T09:24:25.566343514Z         'Accept: application/json, text/plain, */*\r\n' +
2022-09-07T09:24:25.566391883Z         'User-Agent: axios/0.26.1\r\n' +
2022-09-07T09:24:25.566436692Z         'Host: api.audnex.us\r\n' +
2022-09-07T09:24:25.566480525Z         'Connection: close\r\n' +
2022-09-07T09:24:25.566524407Z         '\r\n',
2022-09-07T09:24:25.566564850Z       _keepAliveTimeout: 0,
2022-09-07T09:24:25.566606052Z       _onPendingData: [Function: nop],
2022-09-07T09:24:25.566649197Z       agent: [Agent],
2022-09-07T09:24:25.566695451Z       socketPath: undefined,
2022-09-07T09:24:25.566742453Z       method: 'GET',
2022-09-07T09:24:25.566787156Z       maxHeaderSize: undefined,
2022-09-07T09:24:25.566828807Z       insecureHTTPParser: undefined,
2022-09-07T09:24:25.566874035Z       path: '/books/B01B4YRUKI',
2022-09-07T09:24:25.566916439Z       _ended: true,
2022-09-07T09:24:25.566958323Z       res: [IncomingMessage],
2022-09-07T09:24:25.567003980Z       aborted: false,
2022-09-07T09:24:25.567047192Z       timeoutCb: null,
2022-09-07T09:24:25.567089254Z       upgradeOrConnect: false,
2022-09-07T09:24:25.567131073Z       parser: null,
2022-09-07T09:24:25.567176731Z       maxHeadersCount: null,
2022-09-07T09:24:25.567218933Z       reusedSocket: false,
2022-09-07T09:24:25.567260560Z       host: 'api.audnex.us',
2022-09-07T09:24:25.567352815Z       protocol: 'https:',
2022-09-07T09:24:25.567403429Z       _redirectable: [Writable],
2022-09-07T09:24:25.567446892Z       [Symbol(kCapture)]: false,
2022-09-07T09:24:25.567499606Z       [Symbol(kNeedDrain)]: false,
2022-09-07T09:24:25.567543491Z       [Symbol(corked)]: 0,
2022-09-07T09:24:25.567586900Z       [Symbol(kOutHeaders)]: [Object: null prototype],
2022-09-07T09:24:25.567631734Z       [Symbol(kUniqueHeaders)]: null
2022-09-07T09:24:25.567674467Z     },
2022-09-07T09:24:25.567712666Z     data: '<html>\r\n' +
2022-09-07T09:24:25.567758996Z       '<head><title>504 Gateway Time-out</title></head>\r\n' +
2022-09-07T09:24:25.567819739Z       '<body>\r\n' +
2022-09-07T09:24:25.567863756Z       '<center><h1>504 Gateway Time-out</h1></center>\r\n' +
2022-09-07T09:24:25.567916977Z       '<hr><center>nginx</center>\r\n' +
2022-09-07T09:24:25.567975521Z       `<script>(function(){var js = "window['__CF$cv$params']={r:'746e6b21cadcb2e5',m:'wJ9EgEB8JO5Oc49h0Qrka7oW6shYfELRibWB.WCLGr4-1662543011-0-AS81P9n1xjelRPU0sBr+fJOJcBgIJ1Tmx1sOurSuqXSQlXAHvTd7BIR+HdxVW1siXUT97RM+gAzzL4y6X66mxptw8KnrZb2XyomCHVQ/Tcjy8Airi0rIVhuXGfe9akpUddjTEjsu0tGC0cEGIRnS+pw=',s:[0xbadb1b7d06,0xdf551c09c9],u:'/cdn-cgi/challenge-platform/h/b'};var now=Date.now()/1000,offset=14400,ts=''+(Math.floor(now)-Math.floor(now%offset)),_cpo=document.createElement('script');_cpo.nonce='',_cpo.src='/cdn-cgi/challenge-platform/h/b/scripts/alpha/invisible.js?ts='+ts,document.getElementsByTagName('head')[0].appendChild(_cpo);";var _0xh = document.createElement('iframe');_0xh.height = 1;_0xh.width = 1;_0xh.style.position = 'absolute';_0xh.style.top = 0;_0xh.style.left = 0;_0xh.style.border = 'none';_0xh.style.visibility = 'hidden';document.body.appendChild(_0xh);function handler() {var _0xi = _0xh.contentDocument || _0xh.contentWindow.document;if (_0xi) {var _0xj = _0xi.createElement('script');_0xj.nonce = '';_0xj.innerHTML = js;_0xi.getElementsByTagName('head')[0].appendChild(_0xj);}}if (document.readyState !== 'loading') {handler();} else if (window.addEventListener) {document.addEventListener('DOMContentLoaded', handler);} else {var prev = document.onreadystatechange || function () {};document.onreadystatechange = function (e) {prev(e);if (document.readyState !== 'loading') {document.onreadystatechange = prev;handler();}};}})();</script></body>\r\n` +
2022-09-07T09:24:25.568177770Z       '</html>\r\n'
2022-09-07T09:24:25.568224681Z   },
2022-09-07T09:24:25.568269064Z   isAxiosError: true,
2022-09-07T09:24:25.568338371Z   toJSON: [Function: toJSON]
2022-09-07T09:24:25.568383107Z }
2022-09-07T09:24:25.958678439Z [2022-09-07 09:24:25]  INFO: [CoverManager] Downloaded libraryItem cover "/metadata/items/li_y4xzwlh3qkqu4pk0dl/cover.jpg" from url "https://m.media-amazon.com/images/I/A1t7rja31ML.jpg" for "High Rise"
2022-09-07T09:24:43.382641333Z [2022-09-07 09:24:43]  INFO: Received ping
```

### Steps to reproduce the issue

1. Search for metadata on Audible
2. No results come back.

This doesn't seem to be happening on ALL books, but most of them. 

### Audiobookshelf version

v 2.1.5

### How are you running audiobookshelf?

Docker

**Comment by jt196** [comment]
Can confirm it's working on v2.1.4.

**Comment by jt196** [comment]
Looks like it's working on v 2.1.4

**Comment by advplyr** [comment]
Searching audible on v2.1.5 is working for me. 

That error code is for timing out which could be audnexus having issues or throttling responses.

Nothing was changed with this from v2.1.4 to v2.1.5

**Comment by wtanksleyjr** [comment]
I'm getting the same thing, except I can add that sometimes switching away from and then back to the Match tab INSTANTLY populates it, and other times it just allows the search to work.

I don't find this is specific to Audible, it seems to happen to all of the searches.

**Comment by advplyr** [comment]
We are relying on free APIs to get book metadata so if they decide to throttle your requests or they have some maintenance going on or they are just processing requests slowly there is nothing we can do about it.

**Comment by jt196** [comment]
OK Going to close this as it looks like it's working at the moment on 2.1.5.
